server:
  port: 8050
  
spring:
  application:
    name: Spring-Boot-JPA
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Boot_Demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  thymeleaf:
    cache: false
    
  # Spring Boot Admin相关配置
  boot:
    admin:
      client:
        url:
        # 配置Spring-Boot-Admin监控路径，可多条
        - "http://localhost:8000"

management:
  # actuator监控
  server:
    port: 8059
    servlet:
      context-path: /monitor
  # 接口暴露于屏蔽
  endpoints:
    web:
      exposure:
        include: "*"

# 应用信息   
info:
   app:
      name: Spring-Boot-JPA
      version: 1.0.0
      