server:
  port: 8070
  
spring:
  application:
    name: Spring-Boot-Consul-C
    
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: Spring-Boot-Consul-C