server:
  port: 9999
  
spring:
  application:
    name: Spring-Cloud-Gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 获取服务列表并进行路由
      routes:
      - id: Cloud
        uri: https://github.com/Yommmm/Spring-Cloud-Demo
        predicates: # 断言判断，
        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]