server:
  port: 9999
  
spring:
  application:
    name: Spring-Cloud-Gateway
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 获取服务列表并进行路由，默认关闭；开发环境打开（前后端联调需要），生产环境关闭
#          lower-case-service-id: true # 支持小写的服务名，获取路由打开后才能开启 
      routes:
#      - id: Cloud
#        uri: https://github.com/Yommmm/Spring-Cloud-Demo
#        predicates: # 断言判断
#        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
      - id: Spring-Boot-MyBatis
        uri: lb://Spring-Boot-MyBatis
        predicates: 
        - Path= /boot/v2/**
        filters:
#        - name: Retry # 重试过滤
#          args:
#            retries: 3
#            statuses: BAD_GATEWAY
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: 'forward:/boot/v2/hystrix/fallback'

hystrix: 
  command: 
    fallbackcmd: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 3000
  shareSecurityContext: true