server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1tqmvy486sz6jppyo.mysql.rds.aliyuncs.com:3306/aoptransaction?useSSL=false
    username: root
    password: Hunter123456789

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true