server:
  # 服务端口（使用Docker部署时注意容器开放端口与服务端口保持一致）
  port: 9411
  
spring:
  # 应用名称
  application:
    name: Zipkin-Server

# 应用信息   
info:
   app:
      name: Zipkin-Server
      version: 1.0.0