server:
  port: 8052
  
spring:
  application:
    name: Spring-Boot-MyBatis
    
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Boot_Demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    
mybatis:
  type-aliases-package: com.boot.mapper
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
  